### ISSUE TITLE
How to Incorporate Wall Following with Autonomy Lab

### ISSUE THREAD

**Issue by JordanD7** [AutonomyLab/create_autonomy#83]
Would I be able to use this GitHub to incorporate wall following for my iRobot Create 2?

**Comment by jacobperron** [comment]
Sure, I imagine it is possible. Without any additional sensors you could try using the [raw light sensor values](https://github.com/AutonomyLab/create_robot/blob/9d14e65e5ebf5ebdf48cc63aa2f5844e71d22b9d/create_msgs/msg/Bumper.msg#L16-L23) or the bumpers directly to detect walls. Though, it might be easier to equip your create with a sensor that gives you a concrete distance (e.g. a sonar or IR ranger).

Since this is not a feature I would consider adding directly to `create_autonomy`, I'm closing this ticket. But feel free to continue commenting.

**Comment by JordanD7** [comment]
Thank you for the advice.
