### ISSUE TITLE
Odometry error is huge while rotate in place

### ISSUE THREAD

**Issue by gloria-201** [AutonomyLab/create_autonomy#84]
Hi, I am trying to use Create2 as a move base to implement navigation. 
while using AMCL to localize thre robot, it will fit the map when moving straightly. but when rotating, AMCL will not adjust at all.  As a result, if rotating angle is larger, say 30 degree, only rotation no translation, AMCL will never find the localization. It may be caused by inaccurate rotating angle computed by odometry. when I turn 360 degree. in rviz, it's about 420 degree.  I wonder whether I can increase the axle length value to relieve the huge error?  And I cannot find how to do it.

**Comment by jacobperron** [comment]
In my experience, the odometry from the Create platforms are not that great, especially when it comes to measuring rotation. So, I don't think what you are experiencing is unusual.

Currently, the axle length is hard-coded to a value of [here](https://github.com/AutonomyLab/libcreate/blob/cc95ad35a01835cbc3ead0aef0a09b6c88272626/src/types.cpp#L51) to a value of 0.235m. You could try changing the value and then build libcreate and create_robot from source.

If you would like a programmatic way of changing the value, I'd be happy to review a couple pull requests. First, I would suggest adding setter methods [here](https://github.com/AutonomyLab/libcreate/blob/cc95ad35a01835cbc3ead0aef0a09b6c88272626/include/create/types.h#L59), and then expose a ROS param in the ROS driver [here](https://github.com/AutonomyLab/create_robot/blob/9d14e65e5ebf5ebdf48cc63aa2f5844e71d22b9d/create_driver/src/create_driver.cpp#L49).

I'm going to close ticket in the mean time since I don't think this is a bug in this driver. Please correct me if you think I'm wrong.
